version: '3.7'
services:
  boilerplate-api:
    image: golang:1.20
    expose:
      - "8080:8080" # gRPC
      - "8081:8081" # HTTP
    tty: true
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      APP_NAME: "go-boilerplate"
      APP_ENV: "development"
      APP_PORT: 3000
      APP_DEFAULT_LANG: "en"
      APP_READ_TIMEOUT: 10
      APP_WRITE_TIMEOUT: 10
      POSTGRES_HOST_MASTER: "localhost"
      POSTGRES_PORT_MASTER: 5432
      POSTGRES_USER_MASTER: "postgres"
      POSTGRES_PASSWORD_MASTER: "postgres"
      POSTGRES_DB_MASTER: "postgres"
      POSTGRES_HOST_SLAVE: "localhost"
      POSTGRES_PORT_SLAVE: 5432
      POSTGRES_USER_SLAVE: "postgres"
      POSTGRES_PASSWORD_SLAVE: "postgres"
      POSTGRES_DB_SLAVE: "postgres"
    volumes:
      - ..:/app
    working_dir: /app
    command: |
      go run ./cmd/main.go
    networks:
      - fullstack