// Code generated by MockGen. DO NOT EDIT.
// Source: user_action_history.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// GoMockUserActionHistoryRepo is a mock of UserActionHistoryRepo interface.
type GoMockUserActionHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *GoMockUserActionHistoryRepoMockRecorder
}

// GoMockUserActionHistoryRepoMockRecorder is the mock recorder for GoMockUserActionHistoryRepo.
type GoMockUserActionHistoryRepoMockRecorder struct {
	mock *GoMockUserActionHistoryRepo
}

// NewGoMockUserActionHistoryRepo creates a new mock instance.
func NewGoMockUserActionHistoryRepo(ctrl *gomock.Controller) *GoMockUserActionHistoryRepo {
	mock := &GoMockUserActionHistoryRepo{ctrl: ctrl}
	mock.recorder = &GoMockUserActionHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockUserActionHistoryRepo) EXPECT() *GoMockUserActionHistoryRepoMockRecorder {
	return m.recorder
}

// FindByUserID mocks base method.
func (m *GoMockUserActionHistoryRepo) FindByUserID(ctx context.Context, userID int64) ([]UserActionHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].([]UserActionHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *GoMockUserActionHistoryRepoMockRecorder) FindByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*GoMockUserActionHistoryRepo)(nil).FindByUserID), ctx, userID)
}

// Store mocks base method.
func (m *GoMockUserActionHistoryRepo) Store(ctx context.Context, history UserActionHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *GoMockUserActionHistoryRepoMockRecorder) Store(ctx, history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*GoMockUserActionHistoryRepo)(nil).Store), ctx, history)
}
