name: CD Workflow

on:
  workflow_call:

env:
  GCE_INSTANCE: dev-instance
  GCE_INSTANCE_ZONE: asia-southeast2-a

jobs:
  deployment:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.x'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0.4.0
        with:
#          credentials_json: ${{ secrets.GCE_CREDENTIALS }}
          service_account: ${{ secrets.GCE_CREDENTIALS }}

      - name: Build
        run: go build -o go-boilerplate main.go

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update Service
        run: gcloud compute scp --zone=$GCE_INSTANCE_ZONE ./go-boilerplate $GCE_INSTANCE:~

      - name: Deploy Service
        run: |
          gcloud compute ssh $GCE_INSTANCE \
          --project=$GCE_PROJECT_ID \
          --zone=$GCE_INSTANCE_ZONE \
          --command "fuser -k 8080/tcp || true; cd ~/; nohup ./api > /dev/null 2>&1 &"