name: CD Workflow

on:
  workflow_call:

env:
  GCE_CREDENTIALS: ${{ secrets.GCE_CREDENTIALS }}
  GCE_INSTANCE: dev-instance
  GCE_INSTANCE_ZONE: asia-southeast2-a

jobs:
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.x'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Set up Cloud Authentication
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '$GCE_CREDENTIALS'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Service
        run: |
          gcloud compute ssh --zone=$GCE_INSTANCE_ZONE $GCE_INSTANCE --command "fuser -k 8080/tcp || true; cd ~/; nohup ./api > /dev/null 2>&1 &"