name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    uses: './.github/workflows/lint.yml'
  test:
    uses: './.github/workflows/test.yml'
  deployment:
    needs:
      - lint
      - test
    uses: './.github/workflows/cd.yml'
