name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    uses: './.github/workflows/lint.yml'
  test:
    uses: './.github/workflows/test.yml'
  deployment:
    needs:
      - lint
      - test
    uses: './.github/workflows/cd.yml'
    secrets:
      GCE_CREDENTIALS: ${{ secrets.GCE_CREDENTIALS }}
      GCE_PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
